// This file is auto-generated by create-davepi-ui
// Edit to change authentication configuration

export type AuthMode = 'oauth-only' | 'combined' | 'email-only';
export type OAuthProvider = 'google' | 'github' | 'microsoft' | 'discord';

export interface AuthConfig {
  mode: AuthMode;
  oauthProviders: OAuthProvider[];
}

/**
 * Authentication configuration for this application.
 *
 * - mode: 'email-only' | 'combined' (email + OAuth) | 'oauth-only'
 * - oauthProviders: Array of enabled OAuth providers
 *
 * This config is used by LoginScreen to conditionally render
 * email/password form and OAuth provider buttons.
 */
export const authConfig: AuthConfig = {
  mode: '{{AUTH_MODE}}',
  oauthProviders: {{OAUTH_PROVIDERS}},
};
